service: nuagecron

frameworkVersion: '2 || 3'

custom:
  servicename: ${file(./nuagecron/servicename.json):servicename} 
  pythonRequirements:
    usePoetry: true
    dockerizePip: true
    dockerfile: Dockerfile
  wsgi:
    app: nuagecron.service.app.app
    packRequirements: false

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ SchedulesTable, Arn ]
            - Fn::GetAtt: [ ExecutionsTable, Arn ]
  environment:
    SCHEDULES_TABLE: ${self:service}-schedules
    EXECUTIONS_TABLE: ${self:service}-executions

functions:
  api:
    handler: nuagecron.service.wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  tick:
    handler: nuagecron.domain.lambdas.tick.handler
    events:
      - schedule: rate(2 hours)

plugins:
  - serverless-wsgi
  - serverless-python-requirements

resources:
  Resources:
    SchedulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: schedule_id
            AttributeType: S
        KeySchema:
          - AttributeName: schedule_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-schedules
    ExecutionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: schedule_id
            AttributeType: S
          - AttributeName: execution_time
            AttributeType: 'N'
        KeySchema:
          - AttributeName: schedule_id
            KeyType: HASH
          - AttributeName: execution_time
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:service}-executions
